In [1]:
## Trials for Visualization Assignment 3

In [2]:
pip install xlrd

Requirement already satisfied: xlrd in /opt/miniconda3/envs/dsi_participant_1/lib/python3.10/site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Load libraries

import numpy as np
import matplotlib.pyplot as plt
import PIL
import requests
import seaborn as sns
import pandas as pd
import scipy
import os
from glob import glob

In [4]:
os.getcwd()

'/Users/christineromano/DSI_Course/DSI_Visualization/visualization/02_activities/assignments/Files_for_Assignment_3'

In [5]:
os.listdir()

['9810001901-eng.csv',
 'Off Leash Areas - 4326.csv',
 'licensed-names-for-dogs-2022.xls',
 '.DS_Store',
 'trial.xlsx',
 'Toronto_Pet_Registration_2015_to_2022.xlsx',
 'fsa_counts_2023.xlsx',
 'trial_df.xlsx',
 'Licensed_Dogs_and_Cats.csv',
 'trial2.xlsx',
 'fsa_counts_2024.xlsx',
 'by-forward-sortation-area-fsa 2022.xls',
 'xls_files',
 'assignment_3_trials.ipynb',
 'Licensed Dogs and Cats.xml',
 'Licensed Dogs and Cats (1).csv',
 'Pets_per_year_Toronto_df.xlsx']

In [6]:
# Need to load a csv file and make it into a dataframe

pet_reg_2023_2025_df = pd.read_csv('Licensed_Dogs_and_Cats.csv', index_col=False)
pet_reg_2023_2025_df = pet_reg_2023_2025_df.dropna()
pet_reg_2023_2025_df.info()
pet_reg_2023_2025_df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 180744 entries, 0 to 181059
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   _id            180744 non-null  int64
 1   Year           180744 non-null  int64
 2   FSA            180744 non-null  object
 3   ANIMAL_TYPE    180744 non-null  object
 4   PRIMARY_BREED  180744 non-null  object
dtypes: int64(2), object(3)
memory usage: 8.3+ MB

   _id  Year  FSA ANIMAL_TYPE    PRIMARY_BREED
0    1  2023  M1C         DOG      GOLDEN RETR
1    2  2024  M4T         DOG  OLDENG SHEEPDOG
2    3  2023  M8X         CAT      DOMESTIC SH
3    4  2024  M4J         CAT      DOMESTIC SH
4    5  2023  M3C         CAT      DOMESTIC SH

In [7]:
FSAs_2025 = pet_reg_2023_2025_df['FSA'].unique()
print(FSAs_2025)

['M1C' 'M4T' 'M8X' 'M4J' 'M3C' 'M9R' 'M8V' 'M8Y' 'M4C' 'M4B' 'M9L' 'M8Z'
 'M1P' 'M1E' 'M6M' 'M3K' 'M1H' 'M5M' 'M9A' 'M9P' 'M4P' 'M1G' 'M3J' 'M5V'
 'M3A' 'M9W' 'M9C' 'M4N' 'M9B' 'M2M' 'M5A' 'M1T' 'M6R' 'M1N' 'M6S' 'M1B'
 'M2H' 'M8W' 'M1V' 'M2N' 'M3B' 'M4M' 'M4G' 'M6J' 'M9M' 'M1W' 'M5P' 'M2J'
 'M4L' 'M6C' 'M1K' 'M4W' 'M6N' 'M4V' 'M4S' 'M5R' 'M1L' 'M6E' 'M6G' 'M6B'
 'M4X' 'M2R' 'M6L' 'M5N' 'M1R' 'M4A' 'M6P' 'M6K' 'M4E' 'M1S' 'M3M' 'M2K'
 'M6A' 'M4K' 'M2L' 'M4Y' 'M3H' 'M4R' 'M5J' 'M1J' 'M1X' 'M9V' 'M3L' 'M6H'
 'M9N' 'M1M' 'M5C' 'M2P' 'M5B' 'M4H' 'M5T' 'M5E' 'M3N' 'M5S' 'M5G' 'L6B'
 'L3T' 'M9T' 'N4L' 'L0L' 'M5H' 'L5E' 'L9S' 'K0H' 'K0L' 'K6K' 'L1E' 'L4J'
 'M5L' 'M7A' 'L7E' 'L0S' 'L6X' 'M6T' 'L7G' 'E2L' 'L4A' 'L1S' 'L0K' 'L3P'
 'L5A' 'N3C' 'L3X' 'L4B' 'L2P' 'L3Y' 'L0H' 'L1J' 'N6J' 'L4R' 'L1T' 'L4C'
 'L1N' 'N2J' 'L9V' 'L8N' 'L3Z' 'L4Y' 'L8M' 'L1H' 'K9V']

In [8]:
type(FSAs_2025)

numpy.ndarray

In [9]:
# Just wondering how many forward sortation areas are in Toronto

print(pet_reg_2023_2025_df['FSA'].nunique())

141

In [10]:
# Am noticing that several some documents have extra forward sortation areas.  
# Will drop any FSAs not available since 2015.
# To ensure consistency with data from prior years, need to drop any forward 
# sortation areas that do not begin with "M"
column_titles = ['FSA', 'CAT', 'DOG', 'TOTAL']
# Import data from 2015

pet_reg_2015_df = pd.read_excel('xls_files/by-forward-sortation-area-fsa-2015.xls', header = 2, names = column_titles)
#pet_reg_2015_df = pet_reg_2015_df.rename{' ': }
pet_reg_2015_df.head()

   FSA  CAT   DOG  TOTAL
0  M1B  293   612    905
1  M1C  347   880   1227
2  M1E  490  1004   1494
3  M1G  237   418    655
4  M1H  176   336    512

In [11]:
print(pet_reg_2015_df['FSA'].unique())

['M1B' 'M1C' 'M1E' 'M1G' 'M1H' 'M1J' 'M1K' 'M1L' 'M1M' 'M1N' 'M1P' 'M1R'
 'M1S' 'M1T' 'M1V' 'M1W' 'M1X' 'M2H' 'M2J' 'M2K' 'M2L' 'M2M' 'M2N' 'M2P'
 'M2R' 'M3A' 'M3B' 'M3C' 'M3H' 'M3J' 'M3K' 'M3L' 'M3M' 'M3N' 'M4A' 'M4B'
 'M4C' 'M4E' 'M4G' 'M4H' 'M4J' 'M4K' 'M4L' 'M4M' 'M4N' 'M4P' 'M4R' 'M4S'
 'M4T' 'M4V' 'M4W' 'M4X' 'M4Y' 'M5A' 'M5B' 'M5C' 'M5E' 'M5G' 'M5H' 'M5J'
 'M5M' 'M5N' 'M5P' 'M5R' 'M5S' 'M5T' 'M5V' 'M5W' 'M5X' 'M6A' 'M6B' 'M6C'
 'M6E' 'M6G' 'M6H' 'M6J' 'M6K' 'M6L' 'M6M' 'M6N' 'M6P' 'M6R' 'M6S' 'M8V'
 'M8W' 'M8X' 'M8Y' 'M8Z' 'M9A' 'M9B' 'M9C' 'M9L' 'M9M' 'M9N' 'M9P' 'M9R'
 'M9V' 'M9W']

In [12]:
FSAs_2015 = pet_reg_2015_df['FSA'].unique()
print(FSAs_2015)

['M1B' 'M1C' 'M1E' 'M1G' 'M1H' 'M1J' 'M1K' 'M1L' 'M1M' 'M1N' 'M1P' 'M1R'
 'M1S' 'M1T' 'M1V' 'M1W' 'M1X' 'M2H' 'M2J' 'M2K' 'M2L' 'M2M' 'M2N' 'M2P'
 'M2R' 'M3A' 'M3B' 'M3C' 'M3H' 'M3J' 'M3K' 'M3L' 'M3M' 'M3N' 'M4A' 'M4B'
 'M4C' 'M4E' 'M4G' 'M4H' 'M4J' 'M4K' 'M4L' 'M4M' 'M4N' 'M4P' 'M4R' 'M4S'
 'M4T' 'M4V' 'M4W' 'M4X' 'M4Y' 'M5A' 'M5B' 'M5C' 'M5E' 'M5G' 'M5H' 'M5J'
 'M5M' 'M5N' 'M5P' 'M5R' 'M5S' 'M5T' 'M5V' 'M5W' 'M5X' 'M6A' 'M6B' 'M6C'
 'M6E' 'M6G' 'M6H' 'M6J' 'M6K' 'M6L' 'M6M' 'M6N' 'M6P' 'M6R' 'M6S' 'M8V'
 'M8W' 'M8X' 'M8Y' 'M8Z' 'M9A' 'M9B' 'M9C' 'M9L' 'M9M' 'M9N' 'M9P' 'M9R'
 'M9V' 'M9W']

In [13]:
# Trying to return a list of all FSAs present in both 2015 and 2025
intersection_2015_2025 = np.intersect1d(FSAs_2015, FSAs_2025)
print(intersection_2015_2025)

['M1B' 'M1C' 'M1E' 'M1G' 'M1H' 'M1J' 'M1K' 'M1L' 'M1M' 'M1N' 'M1P' 'M1R'
 'M1S' 'M1T' 'M1V' 'M1W' 'M1X' 'M2H' 'M2J' 'M2K' 'M2L' 'M2M' 'M2N' 'M2P'
 'M2R' 'M3A' 'M3B' 'M3C' 'M3H' 'M3J' 'M3K' 'M3L' 'M3M' 'M3N' 'M4A' 'M4B'
 'M4C' 'M4E' 'M4G' 'M4H' 'M4J' 'M4K' 'M4L' 'M4M' 'M4N' 'M4P' 'M4R' 'M4S'
 'M4T' 'M4V' 'M4W' 'M4X' 'M4Y' 'M5A' 'M5B' 'M5C' 'M5E' 'M5G' 'M5H' 'M5J'
 'M5M' 'M5N' 'M5P' 'M5R' 'M5S' 'M5T' 'M5V' 'M6A' 'M6B' 'M6C' 'M6E' 'M6G'
 'M6H' 'M6J' 'M6K' 'M6L' 'M6M' 'M6N' 'M6P' 'M6R' 'M6S' 'M8V' 'M8W' 'M8X'
 'M8Y' 'M8Z' 'M9A' 'M9B' 'M9C' 'M9L' 'M9M' 'M9N' 'M9P' 'M9R' 'M9V' 'M9W']

In [14]:
type(intersection_2015_2025)

numpy.ndarray

In [15]:
# Convert array to list

FSA_list = intersection_2015_2025.tolist()
print(FSA_list)

['M1B', 'M1C', 'M1E', 'M1G', 'M1H', 'M1J', 'M1K', 'M1L', 'M1M', 'M1N', 'M1P', 'M1R', 'M1S', 'M1T', 'M1V', 'M1W', 'M1X', 'M2H', 'M2J', 'M2K', 'M2L', 'M2M', 'M2N', 'M2P', 'M2R', 'M3A', 'M3B', 'M3C', 'M3H', 'M3J', 'M3K', 'M3L', 'M3M', 'M3N', 'M4A', 'M4B', 'M4C', 'M4E', 'M4G', 'M4H', 'M4J', 'M4K', 'M4L', 'M4M', 'M4N', 'M4P', 'M4R', 'M4S', 'M4T', 'M4V', 'M4W', 'M4X', 'M4Y', 'M5A', 'M5B', 'M5C', 'M5E', 'M5G', 'M5H', 'M5J', 'M5M', 'M5N', 'M5P', 'M5R', 'M5S', 'M5T', 'M5V', 'M6A', 'M6B', 'M6C', 'M6E', 'M6G', 'M6H', 'M6J', 'M6K', 'M6L', 'M6M', 'M6N', 'M6P', 'M6R', 'M6S', 'M8V', 'M8W', 'M8X', 'M8Y', 'M8Z', 'M9A', 'M9B', 'M9C', 'M9L', 'M9M', 'M9N', 'M9P', 'M9R', 'M9V', 'M9W']

In [16]:
FSAs_2015_list = FSAs_2015.tolist()

In [17]:
# Attempting to iterate through the 2023 to 2025 
# dataframe and throughout any FSAs that aren't also present in the 2015 FSA list.

filtered_pet_reg_2023_2025_df = pet_reg_2023_2025_df[pet_reg_2023_2025_df['FSA'].isin(FSA_list)]
filtered_pet_reg_2023_2025_df.head()

   _id  Year  FSA ANIMAL_TYPE    PRIMARY_BREED
0    1  2023  M1C         DOG      GOLDEN RETR
1    2  2024  M4T         DOG  OLDENG SHEEPDOG
2    3  2023  M8X         CAT      DOMESTIC SH
3    4  2024  M4J         CAT      DOMESTIC SH
4    5  2023  M3C         CAT      DOMESTIC SH

In [18]:
print(len(pet_reg_2023_2025_df))
print(len(filtered_pet_reg_2023_2025_df))

180744
180672

In [19]:
df_2023_to_2025_grouped_FSA = filtered_pet_reg_2023_2025_df.groupby(['Year', 'FSA', 'ANIMAL_TYPE']).size()
df_2023_to_2025_grouped_FSA.head(20)

Year  FSA  ANIMAL_TYPE
2023  M1B  CAT            208
           DOG            455
      M1C  CAT            186
           DOG            536
      M1E  CAT            355
           DOG            685
      M1G  CAT            136
           DOG            282
      M1H  CAT             81
           DOG            201
      M1J  CAT            160
           DOG            298
      M1K  CAT            258
           DOG            390
      M1L  CAT            196
           DOG            364
      M1M  CAT            173
           DOG            466
      M1N  CAT            219
           DOG            645
dtype: int64

In [20]:
df_2023_to_2025_grouped_FSA = filtered_pet_reg_2023_2025_df.groupby(['Year', 'FSA', 'ANIMAL_TYPE']).size().unstack(level = -1, fill_value=0)
df_2023_to_2025_grouped_FSA.columns.name = None
df_2023_to_2025_grouped_FSA.head(30)

          CAT  DOG
Year FSA
2023 M1B  208  455
     M1C  186  536
     M1E  355  685
     M1G  136  282
     M1H   81  201
     M1J  160  298
     M1K  258  390
     M1L  196  364
     M1M  173  466
     M1N  219  645
     M1P  198  363
     M1R  134  382
     M1S  147  318
     M1T  150  322
     M1V  146  324
     M1W  161  351
     M1X   18   86
     M2H  138  262
     M2J  271  580
     M2K  107  350
     M2L   50  250
     M2M  127  276
     M2N  398  869
     M2P   38  168
     M2R  166  380
     M3A  198  466
     M3B   76  266
     M3C  184  286
     M3H  192  565
     M3J  131  182

In [21]:
df_2023_to_2025_grouped_FSA_clean = df_2023_to_2025_grouped_FSA.reset_index()
df_2023_to_2025_grouped_FSA_clean.head(30)

    Year  FSA  CAT  DOG
0   2023  M1B  208  455
1   2023  M1C  186  536
2   2023  M1E  355  685
3   2023  M1G  136  282
4   2023  M1H   81  201
5   2023  M1J  160  298
6   2023  M1K  258  390
7   2023  M1L  196  364
8   2023  M1M  173  466
9   2023  M1N  219  645
10  2023  M1P  198  363
11  2023  M1R  134  382
12  2023  M1S  147  318
13  2023  M1T  150  322
14  2023  M1V  146  324
15  2023  M1W  161  351
16  2023  M1X   18   86
17  2023  M2H  138  262
18  2023  M2J  271  580
19  2023  M2K  107  350
20  2023  M2L   50  250
21  2023  M2M  127  276
22  2023  M2N  398  869
23  2023  M2P   38  168
24  2023  M2R  166  380
25  2023  M3A  198  466
26  2023  M3B   76  266
27  2023  M3C  184  286
28  2023  M3H  192  565
29  2023  M3J  131  182

In [22]:
df_2023_to_2025_grouped_FSA_clean['Total'] = df_2023_to_2025_grouped_FSA_clean['CAT'] + df_2023_to_2025_grouped_FSA_clean['DOG']
df_2023_to_2025_grouped_FSA_clean.head(30)

    Year  FSA  CAT  DOG  Total
0   2023  M1B  208  455    663
1   2023  M1C  186  536    722
2   2023  M1E  355  685   1040
3   2023  M1G  136  282    418
4   2023  M1H   81  201    282
5   2023  M1J  160  298    458
6   2023  M1K  258  390    648
7   2023  M1L  196  364    560
8   2023  M1M  173  466    639
9   2023  M1N  219  645    864
10  2023  M1P  198  363    561
11  2023  M1R  134  382    516
12  2023  M1S  147  318    465
13  2023  M1T  150  322    472
14  2023  M1V  146  324    470
15  2023  M1W  161  351    512
16  2023  M1X   18   86    104
17  2023  M2H  138  262    400
18  2023  M2J  271  580    851
19  2023  M2K  107  350    457
20  2023  M2L   50  250    300
21  2023  M2M  127  276    403
22  2023  M2N  398  869   1267
23  2023  M2P   38  168    206
24  2023  M2R  166  380    546
25  2023  M3A  198  466    664
26  2023  M3B   76  266    342
27  2023  M3C  184  286    470
28  2023  M3H  192  565    757
29  2023  M3J  131  182    313

In [23]:
new_column_order = ['FSA', 'CAT', 'DOG', 'Total', 'Year']

# Reorder the columns
Toronto_2023_to_2023_reordered = df_2023_to_2025_grouped_FSA_clean[new_column_order]
Toronto_2023_to_2023_reordered.head(30)

    FSA  CAT  DOG  Total  Year
0   M1B  208  455    663  2023
1   M1C  186  536    722  2023
2   M1E  355  685   1040  2023
3   M1G  136  282    418  2023
4   M1H   81  201    282  2023
5   M1J  160  298    458  2023
6   M1K  258  390    648  2023
7   M1L  196  364    560  2023
8   M1M  173  466    639  2023
9   M1N  219  645    864  2023
10  M1P  198  363    561  2023
11  M1R  134  382    516  2023
12  M1S  147  318    465  2023
13  M1T  150  322    472  2023
14  M1V  146  324    470  2023
15  M1W  161  351    512  2023
16  M1X   18   86    104  2023
17  M2H  138  262    400  2023
18  M2J  271  580    851  2023
19  M2K  107  350    457  2023
20  M2L   50  250    300  2023
21  M2M  127  276    403  2023
22  M2N  398  869   1267  2023
23  M2P   38  168    206  2023
24  M2R  166  380    546  2023
25  M3A  198  466    664  2023
26  M3B   76  266    342  2023
27  M3C  184  286    470  2023
28  M3H  192  565    757  2023
29  M3J  131  182    313  2023

In [24]:
Toronto_2023_to_2023_reordered.tail(30)

     FSA  CAT   DOG  Total  Year
258  M5V  448  1049   1497  2025
259  M6A  121   192    313  2025
260  M6B  128   330    458  2025
261  M6C  168   528    696  2025
262  M6E  266   536    802  2025
263  M6G  285   653    938  2025
264  M6H  443   739   1182  2025
265  M6J  289   580    869  2025
266  M6K  453   771   1224  2025
267  M6L   66   164    230  2025
268  M6M  184   373    557  2025
269  M6N  266   607    873  2025
270  M6P  450   962   1412  2025
271  M6R  266   517    783  2025
272  M6S  303   834   1137  2025
273  M8V  332   808   1140  2025
274  M8W  175   508    683  2025
275  M8X   75   291    366  2025
276  M8Y  128   438    566  2025
277  M8Z  130   418    548  2025
278  M9A  238   619    857  2025
279  M9B  167   621    788  2025
280  M9C  218   635    853  2025
281  M9L   28    67     95  2025
282  M9M   60   141    201  2025
283  M9N  146   284    430  2025
284  M9P  101   262    363  2025
285  M9R  130   337    467  2025
286  M9V  104   242    346  2025
287  M9W  139   352    491  2025

In [25]:
print(df_2023_to_2025_grouped_FSA)

          CAT  DOG
Year FSA
2023 M1B  208  455
     M1C  186  536
     M1E  355  685
     M1G  136  282
     M1H   81  201
...       ...  ...
2025 M9N  146  284
     M9P  101  262
     M9R  130  337
     M9V  104  242
     M9W  139  352

[288 rows x 2 columns]

In [26]:
df_2023_to_2025_grouped_FSA.to_excel('trial2.xlsx')

In [27]:
print(df_2023_to_2025_grouped_FSA.head(50))

          CAT   DOG
Year FSA
2023 M1B  208   455
     M1C  186   536
     M1E  355   685
     M1G  136   282
     M1H   81   201
     M1J  160   298
     M1K  258   390
     M1L  196   364
     M1M  173   466
     M1N  219   645
     M1P  198   363
     M1R  134   382
     M1S  147   318
     M1T  150   322
     M1V  146   324
     M1W  161   351
     M1X   18    86
     M2H  138   262
     M2J  271   580
     M2K  107   350
     M2L   50   250
     M2M  127   276
     M2N  398   869
     M2P   38   168
     M2R  166   380
     M3A  198   466
     M3B   76   266
     M3C  184   286
     M3H  192   565
     M3J  131   182
     M3K   47   105
     M3L   50   138
     M3M  107   215
     M3N  175   215
     M4A   94   158
     M4B  173   357
     M4C  448   948
     M4E  286   914
     M4G  132   650
     M4H   61    46
     M4J  369   954
     M4K  270   836
     M4L  298  1135
     M4M  202   621
     M4N   94   579
     M4P  212   551
     M4R   83   398
     M4S  284   825
     M4T   85   364
     M4V  123   618

In [28]:
# Divide dataframe of 2023 to 2025 data into each year

filtered_pet_reg_2023 = filtered_pet_reg_2023_2025_df[pet_reg_2023_2025_df['Year'] == 2023]
filtered_pet_reg_2023.head()

/var/folders/lk/v5dfvh9d0799xjl8_99hhnhw0000gn/T/ipykernel_34167/2089793892.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered_pet_reg_2023 = filtered_pet_reg_2023_2025_df[pet_reg_2023_2025_df['Year'] == 2023]

   _id  Year  FSA ANIMAL_TYPE PRIMARY_BREED
0    1  2023  M1C         DOG   GOLDEN RETR
2    3  2023  M8X         CAT   DOMESTIC SH
4    5  2023  M3C         CAT   DOMESTIC SH
5    6  2023  M9R         CAT   DOMESTIC SH
9   10  2023  M4C         CAT   DOMESTIC LH

In [29]:
filtered_pet_reg_2024 = filtered_pet_reg_2023_2025_df[pet_reg_2023_2025_df['Year'] == 2024]
filtered_pet_reg_2024.head()

/var/folders/lk/v5dfvh9d0799xjl8_99hhnhw0000gn/T/ipykernel_34167/3849429412.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered_pet_reg_2024 = filtered_pet_reg_2023_2025_df[pet_reg_2023_2025_df['Year'] == 2024]

    _id  Year  FSA ANIMAL_TYPE    PRIMARY_BREED
1     2  2024  M4T         DOG  OLDENG SHEEPDOG
3     4  2024  M4J         CAT      DOMESTIC SH
6     7  2024  M8V         CAT      DOMESTIC SH
8     9  2024  M8Y         CAT      DOMESTIC SH
11   12  2024  M9L         CAT      DOMESTIC SH

In [30]:
filtered_pet_reg_2025 = filtered_pet_reg_2023_2025_df[pet_reg_2023_2025_df['Year'] == 2025]
filtered_pet_reg_2025.head()

/var/folders/lk/v5dfvh9d0799xjl8_99hhnhw0000gn/T/ipykernel_34167/381679097.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered_pet_reg_2025 = filtered_pet_reg_2023_2025_df[pet_reg_2023_2025_df['Year'] == 2025]

    _id  Year  FSA ANIMAL_TYPE PRIMARY_BREED
7     8  2025  M8V         CAT   DOMESTIC SH
26   27  2025  M1G         CAT   DOMESTIC SH
37   38  2025  M5A         CAT   DOMESTIC SH
49   50  2025  M1B         CAT   DOMESTIC SH
58   59  2025  M8W         CAT   DOMESTIC SH

In [31]:
len(filtered_pet_reg_2025)

56774

In [32]:
len(pet_reg_2015_df)

98

In [33]:
# Now that the dataframes have been separated by year, please sort them by FSA and list the totals of dog and cat
filtered_pet_reg_2025_FSA = filtered_pet_reg_2025.groupby(['FSA', 'ANIMAL_TYPE']).size()
print(filtered_pet_reg_2025_FSA.head(20))
print(filtered_pet_reg_2025_FSA.tail(20))

FSA  ANIMAL_TYPE
M1B  CAT            181
     DOG            383
M1C  CAT            174
     DOG            509
M1E  CAT            337
     DOG            576
M1G  CAT            116
     DOG            234
M1H  CAT             92
     DOG            170
M1J  CAT            185
     DOG            232
M1K  CAT            221
     DOG            336
M1L  CAT            184
     DOG            299
M1M  CAT            169
     DOG            426
M1N  CAT            169
     DOG            564
dtype: int64
FSA  ANIMAL_TYPE
M9A  CAT            238
     DOG            619
M9B  CAT            167
     DOG            621
M9C  CAT            218
     DOG            635
M9L  CAT             28
     DOG             67
M9M  CAT             60
     DOG            141
M9N  CAT            146
     DOG            284
M9P  CAT            101
     DOG            262
M9R  CAT            130
     DOG            337
M9V  CAT            104
     DOG            242
M9W  CAT            139
     DOG            352
dtype: int64

In [34]:
fsa_counts_2025 = filtered_pet_reg_2025.groupby(
    ['FSA', 'ANIMAL_TYPE']
).size().unstack(fill_value=0)

print(fsa_counts_2025)

ANIMAL_TYPE  CAT  DOG
FSA
M1B          181  383
M1C          174  509
M1E          337  576
M1G          116  234
M1H           92  170
..           ...  ...
M9N          146  284
M9P          101  262
M9R          130  337
M9V          104  242
M9W          139  352

[96 rows x 2 columns]

In [35]:
type(fsa_counts_2025)

pandas.core.frame.DataFrame

In [36]:
fsa_counts_2024 = filtered_pet_reg_2024.groupby(
    ['FSA', 'ANIMAL_TYPE']
).size().unstack(fill_value=0)

print(fsa_counts_2024)

ANIMAL_TYPE  CAT  DOG
FSA
M1B          219  444
M1C          176  556
M1E          374  665
M1G          127  269
M1H           94  193
..           ...  ...
M9N          151  334
M9P          113  312
M9R          159  376
M9V          117  278
M9W          154  374

[96 rows x 2 columns]

In [37]:
fsa_counts_2023 = filtered_pet_reg_2023.groupby(
    ['FSA', 'ANIMAL_TYPE']
).size().unstack(fill_value=0)

print(fsa_counts_2023)

ANIMAL_TYPE  CAT  DOG
FSA
M1B          208  455
M1C          186  536
M1E          355  685
M1G          136  282
M1H           81  201
..           ...  ...
M9N          136  330
M9P          130  300
M9R          146  373
M9V          138  286
M9W          132  368

[96 rows x 2 columns]

In [38]:
os.listdir()

['9810001901-eng.csv',
 'Off Leash Areas - 4326.csv',
 'licensed-names-for-dogs-2022.xls',
 '.DS_Store',
 'trial.xlsx',
 'Toronto_Pet_Registration_2015_to_2022.xlsx',
 'fsa_counts_2023.xlsx',
 'trial_df.xlsx',
 'Licensed_Dogs_and_Cats.csv',
 'trial2.xlsx',
 'fsa_counts_2024.xlsx',
 'by-forward-sortation-area-fsa 2022.xls',
 'xls_files',
 'assignment_3_trials.ipynb',
 'Licensed Dogs and Cats.xml',
 'Licensed Dogs and Cats (1).csv',
 'Pets_per_year_Toronto_df.xlsx']

In [39]:
pip install xlwt

Requirement already satisfied: xlwt in /opt/miniconda3/envs/dsi_participant_1/lib/python3.10/site-packages (1.3.0)
Note: you may need to restart the kernel to use updated packages.

In [40]:
fsa_counts_2023.to_excel('fsa_counts_2023.xlsx', index = True)
fsa_counts_2024.to_excel('fsa_counts_2024.xlsx', index = True)
fsa_counts_2024.to_excel('fsa_counts_2024.xlsx', index = True)

In [41]:
os.listdir()

['9810001901-eng.csv',
 'Off Leash Areas - 4326.csv',
 'licensed-names-for-dogs-2022.xls',
 '.DS_Store',
 'trial.xlsx',
 'Toronto_Pet_Registration_2015_to_2022.xlsx',
 'fsa_counts_2023.xlsx',
 'trial_df.xlsx',
 'Licensed_Dogs_and_Cats.csv',
 'trial2.xlsx',
 'fsa_counts_2024.xlsx',
 'by-forward-sortation-area-fsa 2022.xls',
 'xls_files',
 'assignment_3_trials.ipynb',
 'Licensed Dogs and Cats.xml',
 'Licensed Dogs and Cats (1).csv',
 'Pets_per_year_Toronto_df.xlsx']

In [42]:
# Have separate files that list, per year, number of cats and dogs per FSA.  
# Concatenate these into one large dataframe.

xls_files = 'xls_files/by*.xls'
all_xls_files = glob(xls_files)
print(all_xls_files)

['xls_files/by-forward-sortation-area-fsa-2020.xls', 'xls_files/by-forward-sortation-area-fsa-2021.xls', 'xls_files/by-forward-sortation-area-fsa-2022.xls', 'xls_files/by-forward-sortation-area-fsa-2019.xls', 'xls_files/by-forward-sortation-area-fsa-2018.xls', 'xls_files/by-forward-sortation-area-fsa-2015.xls', 'xls_files/by-forward-sortation-area-fsa-2016.xls']

In [60]:
xls_files_pets_df = []
rows_to_drop = [0, 1, 2, 3]

for file in all_xls_files:
    dataframe = pd.read_excel(file, header=None, index_col=None)
    dataframe = dataframe.dropna(axis = 1, how = 'all')
    dataframe = dataframe.drop(rows_to_drop, axis = 0)
    filename = os.path.basename(file) 
    name_parts = filename.split('-')
    year_and_xls = name_parts[-1]
    year_parts = year_and_xls.split('.')
    year = year_parts[-2]
    dataframe['Year'] = year
    xls_files_pets_df.append(dataframe)

Toronto_pets_df_concat = pd.concat(xls_files_pets_df, ignore_index=True)
Toronto_pets_df_concat.head(30)

      0    1    2     3  Year
0   M1B  186  440   626  2020
1   M1C  202  592   794  2020
2   M1E  331  640   971  2020
3   M1G  130  273   403  2020
4   M1H   88  225   313  2020
5   M1J  150  271   421  2020
6   M1K  286  421   707  2020
7   M1L  173  368   541  2020
8   M1M  169  447   616  2020
9   M1N  256  623   879  2020
10  M1P  205  340   545  2020
11  M1R  126  376   502  2020
12  M1S  145  309   454  2020
13  M1T  146  288   434  2020
14  M1V  126  315   441  2020
15  M1W  170  332   502  2020
16  M1X   25   86   111  2020
17  M2H  120  255   375  2020
18  M2J  254  503   757  2020
19  M2K   84  291   375  2020
20  M2L   53  247   300  2020
21  M2M  112  299   411  2020
22  M2N  355  743  1098  2020
23  M2P   42  175   217  2020
24  M2R  173  376   549  2020
25  M3A  182  462   644  2020
26  M3B   81  260   341  2020
27  M3C  190  279   469  2020
28  M3H  181  546   727  2020
29  M3J  121  206   327  2020

In [44]:
Toronto_pets_df_concat.columns = ['FSA', 'CAT', 'DOG', 'Total', 'Year']

In [45]:
Toronto_pets_df_concat.to_excel('Toronto_Pet_Registration_2015_to_2022.xlsx')

In [46]:
Toronto_pets_df_concat.head(30)

    FSA  CAT  DOG Total  Year
0   M1B  186  440   626  2020
1   M1C  202  592   794  2020
2   M1E  331  640   971  2020
3   M1G  130  273   403  2020
4   M1H   88  225   313  2020
5   M1J  150  271   421  2020
6   M1K  286  421   707  2020
7   M1L  173  368   541  2020
8   M1M  169  447   616  2020
9   M1N  256  623   879  2020
10  M1P  205  340   545  2020
11  M1R  126  376   502  2020
12  M1S  145  309   454  2020
13  M1T  146  288   434  2020
14  M1V  126  315   441  2020
15  M1W  170  332   502  2020
16  M1X   25   86   111  2020
17  M2H  120  255   375  2020
18  M2J  254  503   757  2020
19  M2K   84  291   375  2020
20  M2L   53  247   300  2020
21  M2M  112  299   411  2020
22  M2N  355  743  1098  2020
23  M2P   42  175   217  2020
24  M2R  173  376   549  2020
25  M3A  182  462   644  2020
26  M3B   81  260   341  2020
27  M3C  190  279   469  2020
28  M3H  181  546   727  2020
29  M3J  121  206   327  2020

In [47]:
Total_pets_reg_Toronto = pd.concat([Toronto_pets_df_concat, Toronto_2023_to_2023_reordered], ignore_index=True)

In [48]:
Total_pets_reg_Toronto.head(30)

    FSA  CAT  DOG Total  Year
0   M1B  186  440   626  2020
1   M1C  202  592   794  2020
2   M1E  331  640   971  2020
3   M1G  130  273   403  2020
4   M1H   88  225   313  2020
5   M1J  150  271   421  2020
6   M1K  286  421   707  2020
7   M1L  173  368   541  2020
8   M1M  169  447   616  2020
9   M1N  256  623   879  2020
10  M1P  205  340   545  2020
11  M1R  126  376   502  2020
12  M1S  145  309   454  2020
13  M1T  146  288   434  2020
14  M1V  126  315   441  2020
15  M1W  170  332   502  2020
16  M1X   25   86   111  2020
17  M2H  120  255   375  2020
18  M2J  254  503   757  2020
19  M2K   84  291   375  2020
20  M2L   53  247   300  2020
21  M2M  112  299   411  2020
22  M2N  355  743  1098  2020
23  M2P   42  175   217  2020
24  M2R  173  376   549  2020
25  M3A  182  462   644  2020
26  M3B   81  260   341  2020
27  M3C  190  279   469  2020
28  M3H  181  546   727  2020
29  M3J  121  206   327  2020

In [49]:
Total_pets_reg_Toronto.tail(30)

     FSA  CAT   DOG Total  Year
949  M5V  448  1049  1497  2025
950  M6A  121   192   313  2025
951  M6B  128   330   458  2025
952  M6C  168   528   696  2025
953  M6E  266   536   802  2025
954  M6G  285   653   938  2025
955  M6H  443   739  1182  2025
956  M6J  289   580   869  2025
957  M6K  453   771  1224  2025
958  M6L   66   164   230  2025
959  M6M  184   373   557  2025
960  M6N  266   607   873  2025
961  M6P  450   962  1412  2025
962  M6R  266   517   783  2025
963  M6S  303   834  1137  2025
964  M8V  332   808  1140  2025
965  M8W  175   508   683  2025
966  M8X   75   291   366  2025
967  M8Y  128   438   566  2025
968  M8Z  130   418   548  2025
969  M9A  238   619   857  2025
970  M9B  167   621   788  2025
971  M9C  218   635   853  2025
972  M9L   28    67    95  2025
973  M9M   60   141   201  2025
974  M9N  146   284   430  2025
975  M9P  101   262   363  2025
976  M9R  130   337   467  2025
977  M9V  104   242   346  2025
978  M9W  139   352   491  2025

In [50]:
Total_pets_reg_Toronto['Year'] = pd.to_numeric(Total_pets_reg_Toronto['Year'], errors='coerce')
Pets_per_year_Toronto = Total_pets_reg_Toronto.sort_values(by = 'Year', ascending= True)
Pets_per_year_Toronto.head(30)

     FSA  CAT   DOG Total  Year
570  M6H  637  1004  1641  2015
565  M6A  144   219   363  2015
564  M5X    0     2     2  2015
563  M5W    6     1     7  2015
562  M5V  291   933  1224  2015
561  M5T  127   201   328  2015
560  M5S  125   228   353  2015
559  M5R  250   657   907  2015
558  M5P  185   714   899  2015
557  M5N  130   456   586  2015
566  M6B  163   469   632  2015
556  M5M  292   988  1280  2015
554  M5H    7    27    34  2015
553  M5G   37    73   110  2015
552  M5E   56   131   187  2015
551  M5C   20    50    70  2015
550  M5B   71   154   225  2015
549  M5A  359   833  1192  2015
548  M4Y  245   539   784  2015
547  M4X  186   380   566  2015
546  M4W  137   616   753  2015
555  M5J   74   157   231  2015
545  M4V  178   654   832  2015
567  M6C  267   672   939  2015
569  M6G  462   730  1192  2015
591  M9R  286   494   780  2015
590  M9P  208   406   614  2015
589  M9N  200   478   678  2015
588  M9M  122   240   362  2015
587  M9L   60   123   183  2015

In [51]:
len(Pets_per_year_Toronto)

979

In [52]:
Pets_per_year_Toronto_df = Pets_per_year_Toronto[Pets_per_year_Toronto['FSA'].isin(FSA_list)]

In [53]:
Pets_per_year_Toronto_df.head(30)

     FSA  CAT   DOG Total  Year
570  M6H  637  1004  1641  2015
565  M6A  144   219   363  2015
562  M5V  291   933  1224  2015
561  M5T  127   201   328  2015
560  M5S  125   228   353  2015
559  M5R  250   657   907  2015
558  M5P  185   714   899  2015
557  M5N  130   456   586  2015
566  M6B  163   469   632  2015
556  M5M  292   988  1280  2015
554  M5H    7    27    34  2015
553  M5G   37    73   110  2015
552  M5E   56   131   187  2015
551  M5C   20    50    70  2015
550  M5B   71   154   225  2015
549  M5A  359   833  1192  2015
548  M4Y  245   539   784  2015
547  M4X  186   380   566  2015
546  M4W  137   616   753  2015
555  M5J   74   157   231  2015
545  M4V  178   654   832  2015
567  M6C  267   672   939  2015
569  M6G  462   730  1192  2015
591  M9R  286   494   780  2015
590  M9P  208   406   614  2015
589  M9N  200   478   678  2015
588  M9M  122   240   362  2015
587  M9L   60   123   183  2015
586  M9C  470  1018  1488  2015
585  M9B  443   889  1332  2015

In [62]:
Pets_per_year_Toronto_df_no_index = Pets_per_year_Toronto_df.reset_index(drop=True)

In [64]:
Pets_per_year_Toronto_df_no_index.head(30)

    FSA  CAT   DOG Total  Year
0   M6H  637  1004  1641  2015
1   M6A  144   219   363  2015
2   M5V  291   933  1224  2015
3   M5T  127   201   328  2015
4   M5S  125   228   353  2015
5   M5R  250   657   907  2015
6   M5P  185   714   899  2015
7   M5N  130   456   586  2015
8   M6B  163   469   632  2015
9   M5M  292   988  1280  2015
10  M5H    7    27    34  2015
11  M5G   37    73   110  2015
12  M5E   56   131   187  2015
13  M5C   20    50    70  2015
14  M5B   71   154   225  2015
15  M5A  359   833  1192  2015
16  M4Y  245   539   784  2015
17  M4X  186   380   566  2015
18  M4W  137   616   753  2015
19  M5J   74   157   231  2015
20  M4V  178   654   832  2015
21  M6C  267   672   939  2015
22  M6G  462   730  1192  2015
23  M9R  286   494   780  2015
24  M9P  208   406   614  2015
25  M9N  200   478   678  2015
26  M9M  122   240   362  2015
27  M9L   60   123   183  2015
28  M9C  470  1018  1488  2015
29  M9B  443   889  1332  2015

In [63]:
Pets_per_year_Toronto_df.columns

Index(['FSA', 'CAT', 'DOG', 'Total', 'Year'], dtype='object')

In [65]:
Pets_per_year_Toronto_df_2 = Pets_per_year_Toronto_df.iloc[:, 0:]  # keep all columns starting from the second
Pets_per_year_Toronto_df_2.columns = ['FSA', 'CAT', 'DOG', 'Total', 'Year']

In [66]:
len(Pets_per_year_Toronto_df_no_index)

955

In [67]:
Pets_per_year_Toronto_df_no_index.to_excel('Pets_per_year_Toronto_df_no_index.xlsx')

In [58]:
pet_reg_2015_df = pd.read_excel('xls_files/by-forward-sortation-area-fsa-2015.xls', header = 2, names = column_titles)
#pet_reg_2015_df = pet_reg_2015_df.rename{' ': }
pet_reg_2015_df.head()

   FSA  CAT   DOG  TOTAL
0  M1B  293   612    905
1  M1C  347   880   1227
2  M1E  490  1004   1494
3  M1G  237   418    655
4  M1H  176   336    512

In [59]:
pet_reg_2016_df = pd.read_excel('xls_files/by-forward-sortation-area-fsa-2016.xls', header = 2, names = column_titles)
#pet_reg_2015_df = pet_reg_2015_df.rename{' ': }
pet_reg_2016_df.head()

   FSA  CAT  DOG  TOTAL
0  M1B  307  612    919
1  M1C  338  852   1190
2  M1E  481  966   1447
3  M1G  216  393    609
4  M1H  182  318    500